version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_DB_NAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${CONTAINER_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}